image: node:alpine


cache:
  paths:  
  - dist


stages:
    - build
    - publish


build:        
    stage: build    
    script:
        - npm install
        - npm run dist
        - tar -C `pwd`/dist -zcvf bundle.tar.gz .
        - "CODECOV_TOKEN=${CODECOV_TOKEN} npm run codecov"

npm_publish:        
    stage: publish
    only:
        - tags
    script:
        - "echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > ~/.npmrc"    
        - npm publish dist


    